- hosts: all
  become: true

  tasks:
    - name: Shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
      ansible_facts['os_family'] == "Debian"
    #- name: gather ansible_facts
    #  ansible.builtin.debug: 
    #    var: ansible_facts // fetch all the facts 
